# Dylan Corbari, 20341171 - Operating Systems Project 1
# ca216/myshell

myshell: myshell.c functions.c
	gcc -o ../bin/myshell myshell.c functions.c

# /*
# Student Name: Dylan Corbari
# Student Number: 20341171
# In submitting this project, I declare that the project material, which I now submit, is my own work. Any assistance received by ways of online resources has been cited and acknowledged within my work. I make this declaration in the knowledge that a breach of the rules pertaining to project submission will carry serious consequences including a mark of 0 for this assignment.
# */
